services:
  site:
    command: sh -c 'export RESEND_API_KEY=$$(cat /run/secrets/RESEND_API_KEY) && pnpm start'
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    secrets:
      - RESEND_API_KEY
    image: spc-site:latest
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    deploy:
      mode: replicated

secrets:
  RESEND_API_KEY:
    external: true
